modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="MIT Licence"
[[mods]] #mandatory
modId="goodmorning" #mandatory
version="1.17.1-1.0" #mandatory
displayName="Good Morning" #mandatory
#logoFile="examplemod.png" #optional
authors="SQwatermark" #optional
description='''
Show title on player wake up.
'''

[[dependencies.goodmorning]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.goodmorning]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"