modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License"
[[mods]] #mandatory
modId="goodmorning" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Good Morning" #mandatory
authors="SQwatermark" #optional
description='''

'''
[[dependencies.goodmorning]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[35,)" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.goodmorning]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.4,1.17)"
   ordering="NONE"
   side="BOTH"
